site_name: Sostenibilidad Aplicada al Sistema Productivo
site_description: Apuntes del módulo de Sostenibilidad de 2.º DAW
site_author: Carlos Alcañiz Carbonell

theme:
  name: material
  language: es
  palette:
    - scheme: default
      primary: orange
      accent: light green
      toggle:
        icon: material/weather-night
        name: Activar modo oscuro
    - scheme: slate
      primary: orange
      accent: light green
      toggle:
        icon: material/weather-sunny
        name: Activar modo claro
  features:
    - navigation.tabs
    - navigation.sections
    - navigation.top
    - navigation.footer
    - content.code.copy
    - search.suggest
    - search.highlight

plugins:
  - search:
      lang: es
  - print-site:
      add_to_navigation: true
      print_page_title: "Versión imprimible"
      print_page_basename: "imprimir"
      add_table_of_contents: true
      toc_title: "Índice"
      toc_depth: 2
      enumerate_headings: false
      enumerate_figures: false
      add_cover_page: true
      add_print_site_banner: false
      add_full_urls: false
      include_css: true
      exclude:
        - index.md
      

markdown_extensions:
  - admonition
  - attr_list
  - md_in_html
  - tables
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true

copyright: >
  © 2026-2027 Carlos Alcañiz ·
  Sostenibilidad Aplicada al Sistema Productivo

extra:
  generator: false
  
extra_css:
  - assets/stylesheets/extra.css

nav:
  - Inicio: index.md
  - UP01. Sostenibilidad, Agenda 2030 y criterios ASG:
      - 1. Relación Curricular: up01/01-index.md
      - 2. Introducción: up01/02-introduccion.md
      - 3. Sostenibilidad y desarrollo sostenible: up01/03-sostenibilidad-y-desarrollo-sostenible.md
      - 4. Marcos internacionales para el desarrollo sostenible: up01/04-marcos-internacionales-para-el-desarrollo-sostenible.md
      - 5. Los criterios ASG: up01/05-criterios-asg.md
      - 6. Grupos de interés y materialidad: up01/06-grupos-de-interes-y-materialidad.md
      - 7. Medición y comunicación de la sostenibilidad: up01/07-medicion-y-comunicacion-de-la-sostenibilidad.md
      - 8. Inversión socialmente responsable: up01/08-inversion-socialmente-responsable.md
      - 9. Sostenibilidad Aplicada al desarrollo Web: up01/09-sostenibilidad-aplicada-al-desarrollo-web.md