site_name: Sostenibilidad Aplicada al Sistema Productivo
site_description: Apuntes del módulo de Sostenibilidad de 2.º DAW
site_author: Carlos Alcañiz Carbonell

theme:
  name: material
  language: es
  palette:
    - scheme: default
      primary: green
      accent: light green
      toggle:
        icon: material/weather-night
        name: Activar modo oscuro
    - scheme: slate
      primary: green
      accent: light green
      toggle:
        icon: material/weather-sunny
        name: Activar modo claro
  features:
    - navigation.tabs
    - navigation.sections
    - navigation.top
    - navigation.footer
    - content.code.copy
    - search.suggest
    - search.highlight

plugins:
  - search:
      lang: es

markdown_extensions:
  - admonition
  - attr_list
  - md_in_html
  - tables
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true

extra_css:
  - assets/stylesheets/extra.css

nav:
  - Inicio: index.md
  - UP01. Introducción a la sostenibilidad:
      - 1. Relación Curricular: up01/index.md
      - 2. Introducción: up01/02-introduccion.md
      - Desarrollo sostenible: up01/02-desarrollo-sostenible.md
      - Agenda 2030: up01/03-agenda-2030.md
      - Objetivos de Desarrollo Sostenible: up01/04-ods.md
      - Grupos de interés y materialidad: up01/07-grupos-de-interes-y-materialidad.md